#import = ["./themes/themes/github_dark_colorblind.yaml"]
[font]
size = 14.0

[font.bold]
family = "Iosevka NF"
style = "Bold"

[font.bold_italic]
family = "Iosevka NF"
style = "Bold Italic"

[font.italic]
family = "Iosevka NF"
style = "Italic"

[font.normal]
family = "Iosevka NF"
style = "Regular"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[[keyboard.bindings]]
chars = "\u001B[105;5u"
key = "I"
mods = "Control"

[window]
decorations = "none"
dynamic_title = false
opacity = 1

[colors]
transparent_background_colors = true
[colors.primary]
#background = "#161619"
background = "#090f17"
dim_foreground    = '#dbdbdb'
bright_foreground = '#d9d9d9'
